---
apiVersion: apps.cloudfoundry.org/v1alpha1
kind: Droplet
metadata:
  name: docker-droplet-guid
  labels:
    apps.cloudfoundry.org/appGuid: my-app-guid
    apps.cloudfoundry.org/buildGuid: my-build-guid
spec:
  type: docker
  appRef:
    kind: App
    apiVersion: apps.cloudfoundry.org/v1alpha1
    name: my-app-guid
  buildRef:
    kind: Build
    apiVersion: apps.cloudfoundry.org/v1alpha1
    name: my-build-guid
status:
  image:
    reference: "cloudfoundry/httpbin"
    pullSecretName: ""
  conditions: []
