---
apiVersion: apps.cloudfoundry.org/v1alpha1
kind: Droplet
metadata:
  name: kpack-droplet-guid
  labels:
    apps.cloudfoundry.org/appGuid: my-app-guid
    apps.cloudfoundry.org/buildGuid: my-build-guid
spec:
  type: kpack
  appRef:
    kind: App
    apiVersion: apps.cloudfoundry.org/v1alpha1
    name: my-app-guid
  buildRef:
    kind: Build
    apiVersion: apps.cloudfoundry.org/v1alpha1
    name: my-build-guid
  registry:
    image: "gcr.io/cf-relint-greengrass/kpack-tutorial-demo-app-local"
    imagePullSecrets:
    - name: "kpack-registry-credentials"
