apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      # TODO: If we use Pack to build this image, the start command provided here will not work.
      - command:
        - /manager
        args:
        - --leader-elect
        image: cloudfoundry/cf-crd-explorations:latest
        # This policy works well for Kind when used with `kind load docker-image cloudfoundry/cf-crd-explorations:latest`
        # imagePullPolicy: Never
        name: manager
        ports:
        - containerPort: 9000
          protocol: TCP
        env:
        - name: REGISTRY_TAG_BASE
          value: "gcr.io/cf-relint-greengrass"
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
