---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  # TODO: Kustomize prefixes the system namespace with 'cf-crd-explorations-'
  # We should figure out how to ensure this is prefixed automatically.
  namespace: cf-crd-explorations-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  # Type LoadBalancer works for most IaaS. This will not work for Kind/Minikube and should be changed to NodePort.
  type: LoadBalancer
  # If you are using a static or pre-allocated IP, uncomment below and provide your IP.
  # loadBalancerIP: INSERT_LB_IP