apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-validation-webhook
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-validation-webhook
rules:
  - apiGroups: [ "apps.cloudfoundry.org" ]
    resources: [ "apps" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-validation-webhook
subjects:
  - kind: ServiceAccount
    name: app-validation-webhook
    namespace: default
roleRef:
  kind: ClusterRole
  name: app-validation-webhook
  apiGroup: rbac.authorization.k8s.io