---
# Defines the CF App
apiVersion: apps.cloudfoundry.org/v1alpha1
kind: CFApp
metadata:
  # apps.cloudfoundry.org/ labels are all managed by a mutating webhook
  labels:
    apps.cloudfoundry.org/appGuid: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
  name: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
  namespace: default
spec:
  name: my-app # validated to be unique per namespace by validating webhook
  envSecretName: "14dcda7d-1fa1-4a91-b437-fbdba20e8c5a-env" # the name of a secret containing a map of multiple environment variables passed to every Process of the App
  currentDropletRef: # starts empty and is filled by CF Shim PATCH endpoint
    apiVersion: "apps.cloudfoundry.org/v1alpha1"
    kind: "CFDroplet"
    name: "1591ee05-e208-4cf3-a662-1c2da42f20a7"
  desiredState: STARTED
  lifecycle: # taken from cf-for-k8s I think we should leave it with a note pointing out how it works in cf-for-k8s 
    # We use this info to make a Builder per app: https://github.com/cloudfoundry/cloud_controller_ng/blob/a698d407d9f11263152cfdc4317f4786567bb16f/lib/cloud_controller/kpack/stager.rb#L153
    type: buildpack
    data:
      buildpacks: []
      stack: cflinuxfs3
status:
  conditions:
  - type: Running
    status: "True"
    reason: Eirini
    message: "Processes are running"
  - type: Restarting # Allows the us to implement the v3 restart app endpoint: https://v3-apidocs.cloudfoundry.org/version/3.100.0/index.html#restart-an-app
    status: "False"
    reason: Restarted
    message: "Restart was successful"
