# permissions for end users to view appmanifests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appmanifest-viewer-role
rules:
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - appmanifests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - appmanifests/status
  verbs:
  - get
