# permissions for end users to edit appmanifests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appmanifest-editor-role
rules:
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - appmanifests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - appmanifests/status
  verbs:
  - get
