# permissions for end users to view builds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: build-viewer-role
rules:
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - builds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - builds/status
  verbs:
  - get
