# permissions for end users to edit droplets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: droplet-editor-role
rules:
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - droplets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - droplets/status
  verbs:
  - get
