# permissions for end users to view droplets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: droplet-viewer-role
rules:
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - droplets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - droplets/status
  verbs:
  - get
