# permissions for end users to edit packages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: package-editor-role
rules:
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - packages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - packages/status
  verbs:
  - get
