# permissions for end users to edit processes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: process-editor-role
rules:
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - processes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.cloudfoundry.org
  resources:
  - processes/status
  verbs:
  - get
