---
apiVersion: apps.cloudfoundry.org/v1alpha1
kind: Process
metadata:
  name: my-process-guid
  labels:
    apps.cloudfoundry.org/appGuid: my-app-guid
    apps.cloudfoundry.org/processGuid: my-process-guid
    apps.cloudfoundry.org/processType: my-process-type
spec:
  appRef:
    kind: App
    apiVersion: apps.cloudfoundry.org/v1alpha1
    name: my-app-guid
  processType: web
  command: ""
  state: STARTED
  healthCheck:
    type: http
    data:
      httpEndpoint: /health
      invocationTimeoutSeconds: 10
      timeoutSeconds: 10
  instances: 5
  memoryMB: 500
  diskQuotaMB: 512
  ports:
    - 8080
  sidecars:
    - name: authenticator
      command: bundle exec run-authenticator
      memoryMB: 800
    - name: upcaser
      command: ./tr-server
      memoryMB: 2000
