---
apiVersion: apps.cloudfoundry.org/v1alpha1
kind: App
metadata:
  name: my-app-guid
  labels:
    apps.cloudfoundry.org/appGuid: my-app-guid
spec:
  name: my-app-name
  desiredState: STARTED
  type: buildpack
  lifecycle:
    data:
      buildpacks: []
      stack: cflinuxfs3
  envSecretName: my-app-guid-env
  currentDropletRef:
    kind: Droplet
    apiVersion: apps.cloudfoundry.org/v1alpha1
    name: build-guid
  processType: web
  command: ""
  healthCheck:
    type: http
    data:
      httpEndpoint: /health
      invocationTimeoutSeconds: 10
      timeoutSeconds: 10
  instances: 5
  memoryMB: 500
  diskQuotaMB: 512
  ports:
    - 8080