---
apiVersion: apps.cloudfoundry.org/v1alpha1
kind: App
metadata:
  name: my-app-guid
  labels:
    apps.cloudfoundry.org/appGuid: my-app-guid
    apps.cloudfoundry.org/appName: my-app-name
spec:
  name: my-app-name
  state: STARTED
  type: buildpack
  lifecycle:
    data:
      buildpacks: []
      stack: cflinuxfs3
  envSecretName: my-app-guid-env
  currentDropletRef:
    kind: Droplet
    apiVersion: apps.cloudfoundry.org/v1alpha1
    name: kpack-droplet-guid
