---
apiVersion: apps.cloudfoundry.org/v1alpha1
kind: Droplet
metadata:
  name: kpack-droplet-guid
  labels:
    cf4k8s.cloudfoundry.org/appGuid: my-app-guid
    cf4k8s.cloudfoundry.org/buildGuid: my-build-guid
spec:
  type: kpack
  appRef:
    kind: App
    apiVersion: apps.cloudfoundry.org/v1alpha1
    name: my-app-guid
  buildRef:
    kind: Build
    apiVersion: apps.cloudfoundry.org/v1alpha1
    name: my-build-guid
status:
  image:
    reference: "relintdockerhubpushbot/dora"
    pullSecretName: ""
  conditions: []
